-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "pricePaidOnReservation" SET DEFAULT 0,
ALTER COLUMN "reservationStartTime" DROP NOT NULL,
ALTER COLUMN "status" DROP DEFAULT;
